<?php

namespace app\api\controller;

use think\Db;
use think\Exception;
use think\Log;


class Coin extends Base
{

    /**
     * @var \ExchApi
     */
    private $exchApi;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->client = new \BtcClient(config('USDT.host'), config('USDT.port'), config('USDT.user'), config('USDT.password'));
        $this->exchApi = new \ExchApi();
    }

    /**
     *钱包列表
     * @param $token
     * @param $page
     * @param $pageSize
     */
    public function CoinList($token, $page = 1, $pageSize = 1000000)
    {
        $data['coin'] = Db('coin')->alias('c')
            ->join('user_coin u', 'u.coin_id = c.coin_id and u.user_id = ' . $this->user_id, 'left')
            ->where(['c.status' => 1])->field('c.coin_id,c.is_recharge,c.is_draw,c.logo,c.name,u.balance,u.wallet,c.is_exchange,c.addtime,c.price_cny,c.price,c.is_c2c,(c.price_cny*c.price) as total,(SELECT sum(num)-sum(deal_num) FROM tp_market as m where m.coin_id = c.coin_id and m.type = 2 and m.user_id=u.user_id and m.status in (0,1)) as market_num ,(SELECT sum(total)+sum(fee) FROM tp_trade as t where t.main_coin_id = c.coin_id and t.type = 1 and t.user_id=u.user_id and t.status=0) as trade_num,(SELECT sum(num) FROM tp_trade as tt where tt.exch_coin_id = c.coin_id and tt.type = 2 and tt.user_id=u.user_id and tt.status=0) as tt_num,(SELECT sum(num) FROM tp_user_cash as uc where uc.coin_id = c.coin_id and uc.user_id=u.user_id and uc.status=0 ) as cash_num,(SELECT sum(fee) FROM tp_trade as tr where tr.main_coin_id = c.coin_id and tr.type = 2 and tr.user_id=u.user_id and tr.status=0) as tr_num')->order('c.sort asc,c.coin_id asc')->paginate(array('list_rows' => $pageSize, 'page' => $page))->toArray();


        foreach ($data['coin']['data'] as $k => $v) {
            if (in_array($v['coin_id'], [1, 23, 24])) {
                $data['coin']['data'][$k]['total'] = Db('price')->where(['date' => date('Ymd'), 'coin_id' => $v['coin_id']])->value('cny_price');
            }
        }


//    $coin = Db('coin')->where(['coin_id'=>1])->field('price,price_cny')->find();

//    $CNY = bcmul($coin['price'],$coin['price_cny'],2);

//    $account = Db('user_account')->where(['user_id'=>$this->user_id])->field('savings,lock,crowd')->find();
//
//    $data['savings'] = bcmul($account['savings'],1,4);
//    $data['savings_CNY'] = bcmul($account['savings'],$CNY,2);
//
//    $data['lock'] = bcmul($account['lock'],1,4);
//    $data['lock_CNY'] = bcmul($account['lock'],$CNY,2);
//
//    if($data['crowd']>0){
//      $data['crowd'] = bcmul($account['crowd'],1,4);
//      $data['crowd_CNY'] = bcmul($account['crowd'],$CNY,2);
//    }else{
//      $data['crowd'] = 0;
//      $data['crowd_CNY'] = 0;
//    }

//    $data['num'] = bcadd(bcadd(bcadd($num, $data['savings_CNY'],2),$data['lock_CNY'],2),$data['crowd_CNY'],2);

        $this->apiResp($data);
    }


    /**
     * 用户充值显示
     * @param $token
     * @param $coin_id
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function show_recharge($token, $coin_id)
    {
//      if($coin_id==1) $this->apiReply(2, '钱包维护中|Wallet maintenance.');
        $user_coin = Db('user_coin')->where(['user_id' => $this->user_id, 'coin_id' => $coin_id])->field('wallet,coin_id')->find();

        $coin = $this->coins[$coin_id];

        if ($user_coin['wallet'] != '') $this->apiReply(1, '', ['wallet' => $user_coin['wallet'], 'coin_id' => $coin_id, 'logo' => $coin['logo'], 'logo_time' => $coin['addtime'], 'name' => $coin['name']]);

        if ($coin['is_recharge'] == 0) $this->apiReply(2, $coin['name'] . '暂未开放充值！|Not yet open recharge.');

        $func = "{$coin['name']}_address";
        $this->$func($coin);

    }


    /**
     * 资产日志
     * @param $token
     * @param $id
     * @param int $page
     * @param int $pageSize
     */
    public function log_coin($token, $id, $page = 1, $pageSize = 10)
    {
        $data = Db('log_coin')->where(['coin_id' => $id, 'user_id' => $this->user_id, 'status' => ['elt', 1]])->field('num,addtime,type,id,union,union_id,id,coin_id')->order('id desc')->paginate(array('list_rows' => $pageSize, 'page' => $page))->toArray();
        $data['type'] = config('log_coin');
        $data['name'] = $this->coins[$id]['name'];
        foreach ($data['data'] as $k => $v) {
            if ($v['coin_id'] == 2 && $v['type'] == 8 && $v['union'] == 'user_cash') {
                $data['data'][$k]['status'] = Db('user_cash')->where(['id' => $v['union_id'], 'coin_id' => $v['coin_id']])->value('status');
            } else {
                $data['data'][$k]['status'] = -2;
            }
        }
        $this->apiResp($data);
    }

    /**
     * 用户钱包
     * @param $token
     * @param $id
     * @param int $page
     * @param int $pageSize
     */
    public function user_wallet($token, $id, $page = 1, $pageSize = 7)
    {
        $get_page = input('$pageSize');
        if ($get_page) {
            $pageSize = $get_page;
        }
        $data = Db('user_wallet')->where(['user_id' => $this->user_id, 'coin_id' => $id])->field('wallet,name,wallet_id')->order('wallet_id desc')->paginate(array('list_rows' => $pageSize, 'page' => $page))->toArray();
        $this->apiResp($data);
    }

    /**
     * 添加钱包地址
     * @param $token
     * @param $coin_id
     * @param $note
     * @param $addr
     */
    public function add_wallet($token, $coin_id, $note, $addr)
    {
        $note = replaceSpecialChar($note);
        $addr = replaceSpecialChar($addr);
        if (!Db('coin')->where(['coin_id' => $coin_id])->count()) {
            $this->apiReply(2, '非法操作！|Illegal operation！');
        }

        if (mb_strlen($addr) == 0) {
            $this->apiReply(2, '请输入有效地址');
        }

//    $this->check_wallet($addr, $coin_id);

        if (mb_strlen($note) == 0 || mb_strlen($note) > 10) {
            $this->apiReply(2, '地址备注1-10个字符!|Address note 1-10 characters!');
        }
        $rst = Db('user_wallet')->insert(['user_id' => $this->user_id, 'coin_id' => $coin_id, 'name' => $note, 'wallet' => $addr, 'status' => 1, 'addtime' => time()]);
        if ($rst) {
            $this->apiReply(1, '添加成功！|Added successfully!');
        } else {
            $this->apiReply(1, '添加失败！|Add failed!');
        }
    }

    /**
     * 编辑钱包地址
     * @param $token
     * @param $id
     * @param $note
     * @param $addr
     */
    public function edit_wallet($token, $id, $note, $addr)
    {
        $note = replaceSpecialChar($note);
        $addr = replaceSpecialChar($addr);
        $data = Db('user_wallet')->where(['wallet_id' => $id, 'user_id' => $this->user_id])->field('coin_id,name,wallet')->find();

        if (!$data) {
            $this->apiReply(2, '非法操作！|Illegal operation！');
        }

        if ($data['name'] == $note && $data['wallet'] == $addr) {
            $this->apiReply(1, '修改成功！|Modified successfully!', $data['coin_id']);
        }

        if (mb_strlen($addr) == 0) {
            $this->apiReply(2, '请输入有效地址');
        }

        if (mb_strlen($addr) == 0) {
            $this->apiReply(2, '请输入有效地址');
        }
//    $this->check_wallet($addr, $id);
        if (mb_strlen($note) == 0 || mb_strlen($note) > 10) {
            $this->apiReply(2, '地址备注1-10个字符!|Address note 1-10 characters!');
        }

        $rst = Db('user_wallet')->where(['wallet_id' => $id, 'user_id' => $this->user_id])->update(['name' => $note, 'wallet' => $addr]);
        if ($rst) {
            $this->apiReply(1, '修改成功！|Modified successfully!', $data['coin_id']);
        } else {
            $this->apiReply(1, '修改失败！|Modification failed!');
        }
    }

    /**
     * 删除钱包地址
     * @param $token
     * @param $id
     * @throws Exception
     * @throws \think\exception\PDOException
     */
    public function del_wallet($token, $id)
    {
        $rst = Db('user_wallet')->where(['wallet_id' => $id, 'user_id' => $this->user_id])->delete();
        if ($rst) {
            $this->apiReply(1, '删除成功！|Delete successful!');
        } else {
            $this->apiReply(1, '删除失败！|Deletion failed!');
        }
    }

    /**
     * 展示钱包地址
     * @param $token
     * @param $id
     */
    public function show_wallet($token, $id)
    {
        $this->apiResp(Db('user_wallet')->where(['wallet_id' => $id, 'user_id' => $this->user_id])->field('name,wallet')->find());
    }

    /**
     * 用户余额
     * @param $token
     * @param $coin_id
     */
    public function user_balance($token, $coin_id)
    {
        $data['balance'] = Db('user_coin')->where(['coin_id' => $coin_id, 'user_id' => $this->user_id])->value('balance');
        $data['name'] = $this->coins[$coin_id]['name'];
        $data['fee'] = $this->coins[$coin_id]['draw_min_fee'];
        $data['min'] = $this->coins[$coin_id]['draw_min_times'];
        $data['rate'] = $this->coins[$coin_id]['draw_rate'];
        $data['usdt'] = Db('user_coin')->where(['coin_id' => 2, 'user_id' => $this->user_id])->value('balance');
//    if($coin_id==2){
        $data['rate_num'] = 5;
//    }else{
//      $data['rate_num'] = 0;
//    }

//    $price = $this->coins[$coin_id]['price'];
//    $price_cny = Db('coin')->where(['coin_id' => $coin_id])->value('price_cny');
        //计算1个通证等于多少RMB
//    $price = bcmul($price, $price_cny, 2);
//    $data['price_cny'] = '1' . $data['name'] . '≈¥' . $price;

        $this->apiResp($data);
    }


    /**
     * 提现发送验证码
     * @param $token
     */
    public function get_change_sms($token)
    {

        // 发送验证码
        $type = 9;
        if ($this->user['code'] == 86) {
            $result = $this->sendSMS($this->user['mobile'], $type);
        } else {
            $result = $this->sendSMS_Global($this->user['mobile'], $type, $this->user['code']);
        }

        if ($result == 'success') {
            $action = array();
            $action['addtime'] = time();
            $action['type'] = $type;
            $action['data'] = $this->user['mobile'];
            session('gt_extract', json_encode($action));
            $this->apiReply(1, '发送成功！', encryption(json_encode($action)));
        } else if ($result == 'exist') {
            $this->apiReply(1, '验证码还未过期，请使用刚才的验证码继续操作！|The verification code has not expired, please continue to operate with the verification code just now', encryption(session('gt_extract')));
        } else {
            $this->apiReply(null, $result);
        }
    }


    /**
     * 提现
     * @param $token
     * @param $user_wallet
     * @param $num
     * @param $coin_id
     * @param $pwd
     */
    public function extract($token, $user_wallet, $num, $coin_id, $pwd)
    {
        $user_wallet = replaceSpecialChar($user_wallet);

        $num = floatval($num);
        if (bccomp($num, 0, 4) == -1)
            $this->apiReply(2, '非法操作！|Illegal operation！');


        $user_paypass = Db('users')->where(['user_id' => $this->user_id, 'status' => 1])->value('paypass');
        if (!$user_paypass) $this->apiReply(888, '请先设置交易密码');
        if (md5($pwd . config('password_str')) != $user_paypass) {
            $text = $this->login_log(-5, $this->user['mobile'], '交易密码不正确！', $this->user_id);
            $this->apiReply(3, $text);
        }

        $fee_num = $this->coins[$coin_id]['draw_min_fee'];
        $min = $this->coins[$coin_id]['draw_min_times'];
        $max = $this->coins[$coin_id]['draw_max_day'];
        $rate = 5; //$this->coins[$coin_id]['draw_rate'];


        //判断单次最小
        if (bccomp($num, $min, 4) == -1) {
            $this->apiReply(2, '最小提现数量为' . $min);
        }

//    $this->check_wallet($user_wallet, $coin_id);

//
//    // 手机验证码是否正确
//    $validate = $this->validateSMS($this->user['mobile'], 9, $validate, $this->user['code']);
//    if ($validate != 'success') {
//      $this->apiResp(null, $validate);
//    }
//    session('gt_extract', null);
        //判断每日总和
        $day_total = Db('user_cash')->where(['date' => date('Ymd'), 'user_id' => $this->user_id, 'coin_id' => $coin_id])->sum('num');

        if (bccomp($max, bcadd($num, $day_total, 4), 4) == -1) {
            $this->apiReply(2, '每日提现上限为' . floatval($max) . '<br/>还可以提取 ' . floatval(bcsub($max, $day_total, 4)));
        }

        Db::startTrans();
        try {
            //查询用户余额
            $user_coin = Db('user_coin')->where(['user_id' => $this->user_id, 'coin_id' => $coin_id])->lock(true)->field('balance,wallet')->find();

            if ($user_coin['wallet'] == $user_wallet) {
                Db::rollback();
                $this->apiReply(2, '请不要给自己转账!|Please do not transfer money to yourself!');
            }

            $count = Db('user_coin')->where(['wallet' => $user_wallet])->count();
            if ($count) $this->apiReply(2, '暂不支持平台转账，请输入其余平台地址!');

            $fee_count = bcadd($num, $rate, 4);

//      //最小手续费判断
//      if (bccomp($fee, $fee_num, 4) == -1) {
//        $fee = $fee_num;
//      }
//
//      if (bccomp($num, $fee, 8) == -1) {
//        Db::rollback();
//        $this->apiReply(2, '数量异常');
//      }

            if (bccomp($user_coin['balance'], $fee_count, 4) == -1) {
                Db::rollback();
                $this->apiReply(2, '余额不足！|not sufficient funds!');
            }

            Db('user_coin')->where(['user_id' => $this->user_id, 'coin_id' => $coin_id])->update(['balance' => bcsub($user_coin['balance'], $fee_count, 4)]);

            $log_id = Db('user_cash')->insertGetId([
                'user_id' => $this->user_id,
                'coin_id' => $coin_id,
                'username' => $this->user['username'],
                'wallet' => $user_wallet,
                'pay_wallet' => $user_coin['wallet'],
                'num' => $num,
                'fee' => 5,
                'type' => 1,
                'status' => 0,
                'date' => date('Ymd'),
                'addtime' => time(),
                'remark' => '',
            ]);

            Db('log_coin')->insert([
                'user_id' => $this->user_id,
                'coin_id' => $coin_id,
                'type' => 8,
                'num' => $fee_count,
                'amount' => $user_coin['balance'],
                'balance' => bcsub($user_coin['balance'], $fee_count, 4),
                'addtime' => time(),
                'status' => 0,
                'union' => 'user_cash',
                'union_id' => $log_id,
                'remark' => '申请提现' . $num . ',手续费' . $rate,
            ]);

            Db::commit();
            $this->apiReply(1, '申请成功，请等待审核！|Application successful, please wait for review！');
        } catch (Exception $e) {
            Db::rollback();
            Log::error($e->getMessage());
            $this->apiReply(2, '申请失败，请重试！|Application failed. Please try again！', $e->getMessage());
        }
    }

    private function check_wallet($wallet, $coin_id)
    {
        if ($coin_id == 1) {

        } else if ($coin_id == 2) {
            if (!preg_match("/^[a-zA-Z0-9]{30,50}$/", $wallet)) $this->apiReply(2, '钱包地址错误！|Wrong wallet address!');
        } else if ($coin_id == 3) {
            if (!preg_match("/^0x[a-zA-Z0-9]{30,50}$/", $wallet)) $this->apiReply(2, '钱包地址错误！|Wrong wallet address!');
        }

    }

    /**
     * 交易账单详情
     * @param $token
     * @param $market_id
     * @param $type
     */
    public function market_details($token, $market_id, $type = '')
    {

        $fee = $this->config['market_fee'];

        if ($type >= 1) {
            //挂买--卖出账单详情  及 自动撤销
            $data = Db('log_market')->where(['log_market_id' => $market_id, 'seller_id' => $this->user_id])->field('price,num,(price*num) as total,addtime,log_market_id as market_id,coin_id')->find();

            //计算手续费
            $data['fee'] = bcmul($data['num'], $fee, 4);

            //撤銷数量 = 出售数量加上手续费
            $data['fee_num'] = bcadd($data['num'], $data['fee'], 4);

        } else {
            //挂卖 - 卖出账单详情  及 撤销
            $data = Db('market')->where(['market_id' => $market_id, 'user_id' => $this->user_id])->field('price,(price*num) as total,fee,status,addtime,market_id,coin_id,num,deal_num')->find();

            //计算未成交数量
            $total_num = bcsub($data['num'], $data['deal_num'], 4);
            //计算剩余数量的手续费
            $to_fee = bcmul($total_num, $fee, 4);
            $data['fee_num'] = bcadd($total_num, $to_fee, 4);
        }

        $data['name'] = $this->coins[$data['coin_id']]['name'];

        $this->apiResp($data);
    }


    /**
     * 交易账单详情
     * @param $token
     * @param $market_id
     */
    public function buy_market_details($token, $market_id)
    {

        //挂买 挂买 买入 及后台强制交易
        $data = Db('log_market')->where(['log_market_id' => $market_id, 'buyer_id' => $this->user_id])->field('price,num,(price*num) as total,addtime,log_market_id as market_id,coin_id,seller_username')->find();

        $data['name'] = $this->coins[$data['coin_id']]['name'];

        $this->apiResp($data);
    }


    /**
     * 充值转入账单详情
     * @param $token
     * @param $id
     * @param $type
     *
     */
    public function cash_details($token, $id, $type)
    {

        //提现转出
        $data = Db('user_cash')->where(['id' => $id, 'user_id' => $this->user_id])->field('num,fee,wallet,remark,transaction_id,addtime,coin_id')->find();
        $data['explorer_url'] = $this->coins[$data['coin_id']]['explorer_url'];
        $data['name'] = $this->coins[$data['coin_id']]['name'];
        $data['type'] = $type;

        $this->apiResp($data);
    }

    /**
     * 充值转入账单详情
     * @param $token
     * @param $id
     * @param $union
     *
     */
    public function trx_coin_details($token, $id, $union)
    {
        //充值转入
        $data = Db($union)->where(['id' => $id, 'user_id' => $this->user_id])->field('amount,to,txid,addtime,coin_id')->find();

        $data['name'] = $this->coins[$data['coin_id']]['name'];
        $data['explorer_url'] = $this->coins[$data['coin_id']]['explorer_url'];

        $this->apiResp($data);
    }

    /**
     * 储蓄钱包账单详情
     * @param $token
     * @param $id
     *
     */
    public function savings_details($token, $id)
    {
        //充值转入
        $data = Db('log_coin')->where(['id' => $id, 'user_id' => $this->user_id])->field('num,addtime,coin_id,type')->find();
        $data['name'] = $this->coins[$data['coin_id']]['name'];

        $this->apiResp($data);
    }


    /**
     * 币币交易账单详情 USDT
     * @param $token
     * @param $trade_id
     * @param $type
     */
    public function trade_details($token, $trade_id, $type = '')
    {

        if ($type >= 1) {
            //币币交易卖出AWT 获得USDT
            $data = Db('log_trade')->where(['log_trade_id' => $trade_id, 'seller_id' => $this->user_id])->field('price,num,total,fee,addtime,log_trade_id,main_coin_id,exch_coin_id')->find();
            $data['type'] = $type;
        } else {
            //币币交易 求购AWT  扣除USDT
            $data = Db('trade')->where(['trade_id' => $trade_id, 'user_id' => $this->user_id])->field('price,total,fee,status,addtime,trade_id,main_coin_id,exch_coin_id,num,deal_num')->find();

            $data['type'] = $type;
        }

        $data['buy_name'] = $this->coins[$data['main_coin_id']]['name']; //awt
        $data['sell_name'] = $this->coins[$data['exch_coin_id']]['name'];//usdt

        $this->apiResp($data);
    }

    /**
     * 币币交易账单详情 WAT
     * @param $token
     * @param $trade_id
     * @param $type
     */
    public function purchase_details($token, $trade_id, $type)
    {

        if ($type == 61) {
            //币币交易 买入增加
            $data = Db('log_trade')->where(['log_trade_id' => $trade_id, 'buyer_id' => $this->user_id])
                ->field('price,total,num,addtime,log_trade_id,main_coin_id,exch_coin_id,seller_username')
                ->find();

            $data['type'] = $type;
        } elseif ($type == 12) {

            //币币交易 出售扣除
            $data = Db('log_trade')->where(['log_trade_id' => $trade_id, 'seller_id' => $this->user_id])
                ->field('price,total,num,addtime,log_trade_id,main_coin_id,exch_coin_id,buyer_username')
                ->find();

            $data['type'] = $type;
        }

        $data['buy_name'] = $this->coins[$data['main_coin_id']]['name']; //awt
        $data['sell_name'] = $this->coins[$data['exch_coin_id']]['name'];//usdt

        $this->apiResp($data);
    }

    /**
     * 币币交易撤销账单详情
     * @param $token
     * @param $id
     *
     */
    public function cancel_details($token, $id)
    {
        //币币交易撤销
        $data = Db('log_coin')->where(['id' => $id, 'user_id' => $this->user_id])->field('num,coin_id,type,union_id')->find();
        $data['addtime'] = Db('trade')->where(['trade_id' => $data['union_id'], 'user_id' => $this->user_id])->value('addtime');
        $data['name'] = $this->coins[$data['coin_id']]['name'];

        $this->apiResp($data);
    }


    /**
     * 获取交易记录
     * @param $token
     * @return string
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function trx($token)
    {
//    if (session('trx_' . $this->user_id))
        //return $this->apiResp(0);

        session('trx_' . $this->user_id, true);
        $wallets = Db('user_coin')
            ->alias('uc')->join('coin c', 'c.coin_id = uc.coin_id')
            ->where(['uc.user_id' => $this->user_id, 'c.coin_id' => 2])
            ->field('uc.wallet, c.coin_id, c.name')->select();
        $count = 0;
        foreach ($wallets as $v) {
            $name = $v['name'] . '_trs';
            $count += $this->$name($v);
        }

        session('trx_' . $this->user_id, false);
        return $this->apiResp($count);
    }

}