<?php

namespace app\api\controller;

use think\Db;
use think\Exception;
use think\Log;
use think\Queue;

class Login extends Common
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 获取注册短信
     * @param $mobile
     * @param $session_id
     * @param $validate_code
     */
    public function gt_reg_sms($mobile, $validate_code, $session_id)
    {
        if (Db('users')->where(array('mobile' => $mobile))->count()) {
            $this->apiReply(2, '该手机号已注册');
        }
        $code = 86;
//        if (Db::name('users')->where(['username' => $username])->count()) {
//            $this->apiResp(null, 'username_used');
//        }
//
//        if (!Db::name('users')->where(['invite' => $invite, 'status' => 1])->count()) {
//            $this->apiResp(null, 'invite_error');
//        }

        if (!$this->check($validate_code)) {
            $this->apiReply(2, '图形验证码错误，请重新输入');
        }

        $type = 1;
        if ($code == '86') {
            if (!$mobile || !is_mobile($mobile)) {
                $this->apiResp(null, 'phone_error_reg');
            }
            $result = $this->sendSMS($mobile, $type);
        } else {
            if (!$mobile) {
                $this->apiResp(null, 'phone_error_reg');
            }
            $result = $this->sendSMS_Global($mobile, $type, $code);
        }

        if ($result == 'success') {
            $action = array();
            $action['addtime'] = time();
            $action['type'] = $type;
            $action['mobile'] = $mobile;
//            $action['username'] = $username;
            session('gt_reg', json_encode($action));
//            $data['session_id'] = session_id();
            $data['action'] = encryption(json_encode($action));
            $this->apiReply(1, '发送成功！|Sent successfully!', $data);
        } else if ($result == 'exist') {
            $data['action'] = encryption(session('gt_reg'));
            $this->apiReply(1, '验证码还未过期，请使用刚才的验证码继续操作！|The verify code has not expired, please use the verify code to continue!', $data);
        } else {
            $this->apiResp(null, $result);
        }
    }

    public function check($code)
    {
        return captcha_check($code);
    }

    /**
     * 检查注册数据方法
     * @param $mobile
     * @param $code
     * @param $password
     * @param $username
     * @param $invite
     * @param $verify
     * @return array|void
     */
    private function reg_validate($mobile, $password, $invite, $verify)
    {
//        $username = replaceSpecialChar($username);
        $code = 86;
        //验证手机号
        if ($code == '86') {
            if (!$mobile || !is_mobile($mobile)) {
                $this->register_log(-4, $mobile, $verify);
                $this->apiResp(null, 'phone_error_reg');
            }
        } else {
            if (!$mobile) {
                $this->register_log(-4, $mobile, $verify);
                $this->apiResp(null, 'phone_error_reg');
            }
        }

        if (Db('Users')->where(array('mobile' => $mobile))->count()) {
            $this->register_log(-5, $mobile, $verify);
            $this->apiResp(null, 'phone_used');
        }

        if (!$password) {
            $this->register_log(-6, $mobile, $verify);
            $this->apiResp(null, 'password_error');
        }

        //验证用户名
//        if (!$username || !is_username($username)) {
//            $this->register_log(-2, $mobile, $verify);
//            $this->apiReply(2, '请输入中文2-5位或英文2-8位的用户名!|Please input the user name of 2-5 characters in Chinese or 2-8 characters in English!');
//        }

//        if (Db('Users')->where(array('username' => $username))->count()) {
//            $this->register_log(-3, $mobile, $verify);
//            $this->apiResp(null, 'username_used');
//        }
        // 获取推荐人信息
        $pid = Db('users')->where(['invite' => $invite, 'status' => 1])->value('user_id');
        if (!$pid) {
//            $this->register_log(-9, $mobile, $verify);
//            $this->apiResp(null, 'invite_error');
            $pid = 10001;
        }

        // 生成邀请码
        do {
            $invite = chr(rand(65, 72)) . rand(1000000, 9999999);
        } while (Db('users')->where('invite', $invite)->count());

        do {
            $number = rand(10000, 1000000);
        } while (Db('users')->where('number', $number)->count());

        $ip = long2ip(request()->ip(1));
        $url = "http://ip.taobao.com/service/getIpInfo.php?ip=" . $ip;
        $arr = json_decode(@file_get_contents($url));

        if ((string)$arr->code == '1') {
            $address = '';
        } else {
            $data = (array)$arr->data;
            if ($data['county'] = 'XX') {
                $data['county'] = '';
            }
            $address = $data['region'] . $data['city'] . $data['county'];
        }

        $data = [
            'username' => $mobile,
            'code' => $code,
            'mobile' => trim($mobile),
            'password' => md5($password . config('password_str')),
            'paypass' => '',
            'invite' => $invite,
            'avatar' => '',
            'pid' => $pid,
            'addtime' => time(),
            'update' => time(),
            'reg_ip' => request()->ip(1),
            'deleted' => 0,
            'status' => 1,
            'number' => $number,
            'address' => $address
        ];

        return $data;
    }

    /**
     * * 用户注册
     * @param $verify
     * @param $mobile
     * @param $code
     * @param $password
     * @param $username
     * @param $invite
     * @param $action
     * @param $session_id
     */

    public function register($mobile, $password, $verify, $invite, $action, $session_id)
    {
        $code = 86;
//        session_id($session_id);
        // 判断同IP注册次数
//        if (Db('log_register')->where(['ip' => request()->ip(1), 'addtime' => ['gt', time() - 3600], 'status' => 1])->count() >= 5) {
//            $this->register_log(-1, $mobile, $verify);
//            $this->apiReply(2, '当前IP注册用户过多，请稍后再试!|There are too many registered users of IP, please try again later!');
//        }

//        $this->apiReply(2, '注册接口暂停服务！|注册接口暂停服务！');

        $action_id = session('gt_reg');
        if (!$action_id || encryption($action_id) != $action) $this->apiReply(2, '请点击获取验证码！|Please click to get the verification code!');

        // 验证注册参数
        $data = $this->reg_validate($mobile, $password, $invite, $verify);

        // 手机验证码是否正确
        $validate = $this->validateSMS($mobile, 1, $verify, $code);
        if ($validate != 'success') {
            $this->register_log(-7, $mobile, $verify);
            $this->apiResp(null, $validate);
        }
        session('gt_reg', null);

        // 启动事务
        Db::startTrans();
        try {
            $user_id = Db('users')->insertGetId($data);
            Db('user_rela')->insert(['user_id' => $user_id, 'pid' => $data['pid'], 'addtime' => strtotime(date('Y-m-d', time()))]);
            Db('user_rela')->where(['user_id' => $data['pid']])->setInc('direct');
//            Db('user_account')->insert(['user_id' => $user_id]);

            Db('user_coin')->insert(['user_id' => $user_id, 'coin_id' => 1]);
            Db('user_coin')->insert(['user_id' => $user_id, 'coin_id' => 2]);
            Db('user_coin')->insert(['user_id' => $user_id, 'coin_id' => 23]);
            Db('user_coin')->insert(['user_id' => $user_id, 'coin_id' => 24]);
//            $coin = $this->coins;
//            foreach ($coin as $k => $v) {
//                if (in_array($v['coin_id'], [1, 2,23])) {
//                    Db('user_coin')->insert(['user_id' => $user_id, 'coin_id' => $v['coin_id']]);
//                }
//            }

//            $send_num = 100;
//            //log_coin表添加数据
//            Db('log_coin')->insertGetId([
//                'user_id' => $user_id,
//                'coin_id' => 1,
//                'type' => 99,
//                'num' => $send_num,
//                'amount' => 0,
//                'balance' => $send_num,
//                'addtime' => time(),
//                'status' => 1,
//                'remark' => '注册赠送100个AWT',
//            ]);
//
//            Db('user_coin')->where(['user_id' => $user_id, 'coin_id' => 1])->update(['balance' => $send_num]);

            $this->register_log(1, $mobile, $verify);
            Db::commit();

            Queue::push('app\api\job\UserRela', ['user_id' => $user_id, 'pid' => $data['pid']]); // 添加队列

            $data['yes'] = 'login';
            $data['no'] = '';
            $data['down_msg'] = '注册成功！是否立即下载APP';
            $data['down_yes'] = 'down';
            $data['down_no'] = '';

            $this->apiReply(1, '注册成功！是否立即登陆？|Registered successfully! Are you login immediately?', $data);

        } catch (Exception $e) {
            Log::error($e->getMessage());
            // 回滚事务
            Db::rollback();
            $this->register_log(-8, $mobile, $verify);
            $this->apiResp(['msg' => $e->getMessage()], 'sys_busy');
        }
    }

    //注册时候的记录
    private function register_log($status, $mobile, $code)
    {
        Db('log_register')->insert(array('code' => $code, 'mobile' => $mobile, 'addtime' => time(), 'ip' => request()->ip(1), 'status' => $status));
    }


    /** 用户登录
     * @param $mobile
     * @param $password
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function login($mobile, $password)
    {

        $info = Db('users')->where(['mobile' => $mobile])->field('`user_id`, `username`, `password`, `status`')->find();

        if (!$info) {
            $this->login_log(-1, $mobile, '用户不存在，请先注册！|User name does not exist, please register!');
            $this->apiReply(2, '用户不存在，请先注册！|User name does not exist, please register!');
        }

        if ($info['status'] <= 0) {
            $object = Db('log_action')->where(['union_id' => $info['user_id'], 'union' => 'users'])->order('id desc')->value('object');
//            if ($object !== null) {
//                $this->apiReply(2, $object . '请联系客服!|Please contact customer service!');
//            } else {
//                $this->apiReply(2, '账号异常，请联系客服!|The account is abnormal, please contact the customer service!');
//            }
            $this->apiReply(2, '账号异常，请联系客服!|The account is abnormal, please contact the customer service!');
            $this->login_log(-2, $mobile, '账号被冻结！|Account frozen!');
        }

        // 下面是登陆判断是否有错误日志
        $user_lock_time = $this->redis->zScore('user_lock', $info['user_id'] . ':' . $mobile) - time();
        if ($user_lock_time >= 0) {
            if ($user_lock_time > 3600) {
                $time = ceil($user_lock_time / 3600) . '小时';
            } else {
                $time = ceil($user_lock_time / 60) . '分钟';
            }
            $this->login_log(-4, $mobile, '登录密码或者交易密码错误超过5次，账户冻结！');
            $this->apiReply(2, '登录密码或者交易密码错误超过5次，账户冻结，' . $time . '后重试！|Password or identity check error more than 5 times, account frozen, try again after' . $time);
        }

        if (md5($password . config('password_str')) != $info['password']) {
            $text = $this->login_log(0, $mobile, '登陆密码错误！', $info['user_id']);
            $this->apiReply(2, $text);
        }

        // 登录成功，添加登录日志
        $this->login_log(1, $mobile, '登陆成功！|Login successful!', $info['user_id']);

        // 登录成功，清空log_login表当天登录错误次数
        Db('log_login')->where(['user_id' => $info['user_id'], 'status' => 0])->setField('status', 2);

        $time = time();

        session($info['user_id'] . '.' . $mobile, $time); // 单点登陆session
        session('session_id', session_id()); // 单点登陆session

        $this->redis->hSet('user:' . $info['user_id'], 'session', session_id());

        $userInfo = $this->loadUser($info['user_id']);
        cache('cache_userinfo_' . $info['user_id'], $userInfo);

        $token = authcode($info['user_id'] . '+' . $mobile . '+' . $time, 'ENCODE'); // 当前登录时间
        session('token', $token);
        $userInfo['token'] = $token;
        $this->apiResp($userInfo);
    }


    /**
     * app直接登陆
     * @param $token
     */
    public function app_login($token)
    {
        $token = input('token');
        if (!$token)
            $this->apiReply(2, '非法请求');
        $arr = explode('+', authcode($token, 'DECODE'));
        if (!$arr[0])
            $this->apiResp(null, 'token_error');


        $mobile = $arr[1];
        $info = Db::name('users')->where(['mobile' => $mobile])->field('`user_id`,`password`,`status`,`freeze_time`')->find();
        if (!$info) {
            $this->login_log(-1, $mobile, '手机号码不存在！');
            $this->apiReply(2, '手机号码不存在！');
        }

        //检查是否有不良记录
        if ($info['freeze_time'] >= time()) {
            $this->apiReply(2, "有不良记录，账户冻结！<br/>剩余：" . $this->get_time($info['freeze_time'] - time()));
        } else {
            if ($info['freeze_time'] != 0) {
                //不良记录时间到期
                $info['status'] = 1;
                Db::name('users')->where(['mobile' => $mobile])->update(['status' => 1, 'freeze_time' => 0]);
            }
        }

        if ($info['status'] === 0) {
            $this->login_log(-1, $mobile, '账号被冻结！');
            $this->apiResp(null, 'phone_error');
        }

        // 下面是登陆判断是否有错误日志
        $user_lock_time = $this->redis->zScore('user_lock', $info['user_id'] . ':' . $mobile) - time();
        if ($user_lock_time >= 0) {
            if ($user_lock_time > 3600) {
                $time = ceil($user_lock_time / 3600) . '小时';
            } else {
                $time = ceil($user_lock_time / 60) . '分钟';
            }
            $this->login_log(-4, $mobile, '登录密码或者交易密码错误超过5次，账户冻结！');
            $this->apiReply(2, '登录密码或者交易密码错误超过5次，账户冻结，' . $time . '后重试！|Password or identity check error more than 5 times, account frozen, try again after' . $time);
        }

        //登录成功，添加登录日志
        $this->login_log(1, $mobile, '登陆成功！', $info['user_id']);

        //登录成功，清空log_login表当天登录错误次数
        Db::name('log_login')->where(['user_id' => $info['user_id'], 'status' => 0])->setField('status', 2);

        $time = time();
//        session(['name'=>$info['user_id'] . '.' . $mobile,'expire'=>3600*24], $time); // 登录时长1天
        session($info['user_id'] . '.' . $mobile, $time); // 单点登陆session
        session('session_id', session_id()); // 单点登陆session

        $this->redis->hSet('user:' . $info['user_id'], 'session', session_id());

        $userInfo = $this->loadUser($info['user_id']);

        cache('cache_userinfo_' . $info['user_id'], $userInfo);

        $token = authcode($info['user_id'] . '+' . $mobile . '+' . $time, 'ENCODE'); // 当前登录时间
        $userInfo['token'] = $token;

        $this->apiResp($userInfo);
    }

    protected function get_time($time)
    {
        $str = '';
        $d = floor($time / (3600 * 24));
        $str .= $d . '天';
        $h = floor(($time - $d * 3600 * 24) / 3600);
        $str .= $h . '小时';
        $m = floor(($time - $d * 3600 * 24 - $h * 3600) / 60);
        $str .= $m . '分钟';
        $s = $time - $d * 3600 * 24 - $h * 3600 - $m * 60;
        $str .= $s . '秒';
        return $str;
    }

    /**
     * 忘记密码发送验证码
     * @param $session_id
     * @param $mobile
     * @param $validate_code
     */
    public function get_forget_sms($mobile, $validate_code, $session_id)
    {
        $code = 86;
        $info = Db('users')->where(['mobile' => $mobile])->field('`code`,`mobile`,`username`,`status`')->find();

        if (!$info || $info['status'] === 0) $this->apiResp(null, 'user_not_exist');

        if (!$this->check($validate_code)) {
            $this->apiReply(2, '图形验证码错误，请重新输入');
        }

        $type = 2;
        if ($code == '86') {
            if (!$mobile || !is_mobile($mobile)) {
                $this->apiResp(null, 'phone_error_reg');
            }
            $result = $this->sendSMS($mobile, $type);
        } else {
            if (!$mobile) {
                $this->apiResp(null, 'phone_error_reg');
            }
            $result = $this->sendSMS_Global($mobile, $type, $code);
        }

        if ($result == 'success') {
            $action = array();
            $action['addtime'] = time();
            $action['type'] = $type;
            $action['mobile'] = $mobile;
            $action['username'] = $info['username'];
            session('gt_forget', json_encode($action));
            $data['session_id'] = session_id();
            $data['action'] = encryption(json_encode($action));
            $this->apiReply(1, '发送成功！|Sent successfully!', $data);
        } else if ($result == 'exist') {
            $data['action'] = encryption(session('gt_forget'));
            $this->apiReply(1, '验证码还未过期，请使用刚才的验证码继续操作！|The verify code has not expired, please use the verify code to continue!', $data);
        } else {
            $this->apiResp(null, $result);
        }
    }


    /**
     * 修改密码
     * @param $mobile
     * @param $code
     * @param $password
     * @param $action
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     * @param $session_id
     */
    public function forget($mobile, $code, $password, $action, $session_id)
    {
        session_id($session_id);
        $action_id = session('gt_forget');
        if (!$action_id || encryption($action_id) != $action) $this->apiReply(2, '请点击获取验证码！|Please click to get the verification code!');

        $user = Db('users')->where(['mobile' => $mobile])->field('`code`,`username`,`status`,`password`,`user_id`,`paypass`')->find();
        if (!$user) $this->apiReply(2, '用户名不存在|User name doesn\'t exist!');
        if ($user['status'] === 0) $this->apiReply(2, '用户没激活或者被禁用！|The user is not active or disabled');

        if (md5($password . config('password_str')) == $user['password']) {
            $this->apiReply(2, '新密码和当前密码不能相同！|The current password and the new password cannot be the same!');
        }

        if (md5($password . config('password_str')) == $user['paypass']) {
            $this->apiReply(2, '新密码和交易密码不能相同！|The new password and trade password cannot be the same!');
        }

        // 手机验证码是否正确
        $validate = $this->validateSMS($mobile, 2, $code, $user['code']);
        if ($validate != 'success') {
            $this->apiResp(null, $validate);
        }
        session('gt_forget', null);

        Db::startTrans();
        try {
            Db('users')->where(['user_id' => $user['user_id']])->update(['password' => md5($password . config('password_str'))]);
            Db('log_change_pass')->insert(['user_id' => $user['user_id'], 'type' => 416, 'intro' => '修改登录密码', 'old' => '', 'new' => $password, 'addtime' => time()]);
            Db('log_login')->where(['user_id' => $user['user_id'], 'status' => 0])->setField('status', 2);
            Db::commit();
            $this->apiReply(1, '修改成功|Modify success');
        } catch (Exception $e) {
            Log::error($e->getMessage());
            Db::rollback();
            $this->apiReply(2, '修改失败！|Modify failed!');
        }
    }

    /**
     * 获取国别码(Redis)
     */
    public function country()
    {
        $country = Db::name('country')->where('status', 1)->field('`code`,`name`')->order('`sorting` ASC')->select();
        $this->apiResp($country);
    }

    //todo  一下的方法都需要重新规划

    /**
     * 系统版本信息
     */
    public function app()
    {
        $this->apiResp([
            "android" => [
                "version" => "1.0.11",
                "download" => "https://html.changex.info/#down",
                "app_store" => "https://trade-changex-oss.oss-cn-shanghai.aliyuncs.com/app/v1.0.11/ChangeEx.apk"
            ],
            "ios" => [
                'version' => "1.0.11",
                "download" => "https://html.changex.info/#down",
                'app_store' => 'itms-services://?action=download-manifest&url=https://trade-changex-oss.oss-cn-shanghai.aliyuncs.com/app/v1.0.11/manifest-3.plist',
            ]
        ]);
    }

    /**
     * 引导页
     */
    public function loading()
    {
        $data = Db('first_picture')->where(['type' => 1, 'status' => 1])->order('sorting asc')->field('url, addtime, jump_url, title')->select();
        $this->apiResp($data);
    }

    public function service()
    {
        $this->apiResp([
            'src' => 'https://www.365webcall.com/chat/ChatWin3.aspx?settings=mw7m0m0m7PN0PPz3A7mXNIz3A7mPXz3A66mmP7&LL=0'
        ]);
    }


    public function gt_session_id()
    {
        $data['session_id'] = session_id();
        $this->apiResp($data);
    }

    //添加FID
    public function add_fid()
    {
        $data = db('fid_user')->where(['is_add' => 0])->group('mobile')->select();

        foreach ($data as $v) {
            $user_id = db('users')->where(['mobile' => $v['mobile']])->value('user_id');
            if ($user_id) {
                $old_balance = db('user_coin')->where(['user_id' => $user_id, 'coin_id' => 24])->value('balance');
                if ($old_balance < 5000) {
                    db('fid_user')->where(['mobile' => $v['mobile']])->update(['is_add' => 1]);
                    $new_balance = bcadd($old_balance, 5000, 8);
                    //更新余额
                    db('user_coin')->where(['user_id' => $user_id, 'coin_id' => 24])->update(['balance' => $new_balance]);
                    //添加日志
                    Db('log_coin')->insertGetId([
                        'user_id' => $user_id,
                        'coin_id' => 24,
                        'type' => 82,
                        'num' => 5000,
                        'amount' => $old_balance,
                        'balance' => $new_balance,
                        'addtime' => time(),
                        'status' => 1,
                        'remark' => 'FID会员增加5000',
                    ]);
                } else {
                    db('fid_user')->where(['mobile' => $v['mobile']])->update(['is_add' => 3]);
                }
            }
        }
    }

    public function otc_buy_notice()
    {
        $path = RUNTIME_PATH . 'otc_buy_notice/';
        if (!is_dir($path)) {
            mkdir($path, 0777, true);
        }
        file_put_contents($path . 'notify_' . date('Ymd') . '.log', date('Y-m-d H:i:s') . "\n" . file_get_contents("php://input") . "\n", FILE_APPEND);

        $count = $_POST['count'];
        $merchantCustId = $_POST['merchantCustId'];
        $myOrderNo = $_POST['merchantOrderNo'];
        $coinPayNo = $_POST['orderNo'];
        $status = $_POST['status'];
        $sign = $_POST['sign'];
        $msg = $_POST['msg'];

        $data = Array('count' => $count, 'merchantCustId' => $merchantCustId, 'orderNo' => $coinPayNo, 'merchantOrderNo' => $myOrderNo, 'status' => $status, 'msg' => $msg, 'sign' => $sign);

        if (!self::verify($data, $sign)) {
            echo '验签不通过';
            file_put_contents($path . 'notify_' . date('Ymd') . '.log', date('Y-m-d H:i:s') . "\n" . '验签失败' . "\n", FILE_APPEND);
            exit;
        }

        //查询订单
        $order = db('otc_buy')->where(['orderNo' => $myOrderNo])->find();

        if (!$order) {
            echo '订单不存在';
            file_put_contents($path . 'notify_' . date('Ymd') . '.log', date('Y-m-d H:i:s') . "\n" . '订单不存在' . "\n", FILE_APPEND);
            exit;
        }
        if ($order['status'] != 0) {
            echo '不可重复处理';
            file_put_contents($path . 'notify_' . date('Ymd') . '.log', date('Y-m-d H:i:s') . "\n" . '不可重复处理' . "\n", FILE_APPEND);
            exit;
        }
        if ($order['amount'] != $count) {
            echo '金额不符';
            file_put_contents($path . 'notify_' . date('Ymd') . '.log', date('Y-m-d H:i:s') . "\n" . '金额不符' . "\n", FILE_APPEND);
            exit;
        }
        if ($status == 'Failed') {
            //修改订单状态
            db('otc_buy')->where(['orderNo' => $myOrderNo])->update(['status' => -1]);
            file_put_contents($path . 'notify_' . date('Ymd') . '.log', date('Y-m-d H:i:s') . "\n" . $msg . "\n", FILE_APPEND);
            echo $msg;
        }
        if ($status == 'Done' && $count >= $order['amount']) {
            Db::startTrans();
            try {
                //买币成功，给客户增加余额
                $old_balance = db('user_coin')->where(['user_id' => $order['user_id'], 'coin_id' => $order['coin_id']])->lock(true)->value('balance');
                $new_balance = bcadd($old_balance, $order['amount'], 8);
                db('user_coin')->where(['user_id' => $order['user_id'], 'coin_id' => $order['coin_id']])->update(['balance' => $new_balance]);
                //日志
                Db('log_coin')->insert([
                    'user_id' => $order['user_id'],
                    'coin_id' => $order['coin_id'],
                    'type' => 120,
                    'num' => $order['amount'],
                    'amount' => $old_balance,
                    'balance' => $new_balance,
                    'addtime' => time(),
                    'status' => 1,
                    'remark' => 'OTC购买',
                    'union' => 'otc_buy',
                    'union_id' => $order['id'],
                ]);
                //修改订单状态
                db('otc_buy')->where(['orderNo' => $myOrderNo])->update(['status' => 1]);

                Db::commit();
                echo 'OK';
            } catch (Exception $e) {
                file_put_contents($path . 'notify_' . date('Ymd') . '.log', date('Y-m-d H:i:s') . "\n" . $e->getMessage() . "\n", FILE_APPEND);
                Db::rollback();
                echo 'fail';
            }
        }
    }

    public function otc_sell_notice()
    {
        $path = RUNTIME_PATH . 'otc_sell_notice/';
        if (!is_dir($path)) {
            mkdir($path, 0777, true);
        }
        file_put_contents($path . 'notify_' . date('Ymd') . '.log', date('Y-m-d H:i:s') . "\n" . file_get_contents("php://input") . "\n", FILE_APPEND);

        $count = $_POST['count'];
        $merchantCustId = $_POST['merchantCustId'];
        $myOrderNo = $_POST['merchantOrderNo'];
        $coinPayNo = $_POST['orderNo'];
        $status = $_POST['status'];
        $sign = $_POST['sign'];
        $msg = $_POST['msg'];

        $data = Array('count' => $count, 'merchantCustId' => $merchantCustId, 'orderNo' => $coinPayNo, 'merchantOrderNo' => $myOrderNo, 'status' => $status, 'msg' => $msg, 'sign' => $sign);

        if (!self::verify($data, $sign)) {
            echo '验签不通过';
            file_put_contents($path . 'notify_' . date('Ymd') . '.log', date('Y-m-d H:i:s') . "\n" . '验签失败' . "\n", FILE_APPEND);
            exit;
        }

        //查询订单
        $order = db('otc_sell')->where(['orderNo' => $myOrderNo])->find();

        if (!$order) {
            echo '订单不存在';
            file_put_contents($path . 'notify_' . date('Ymd') . '.log', date('Y-m-d H:i:s') . "\n" . '订单不存在' . "\n", FILE_APPEND);
            exit;
        }
        if ($order['status'] != 0) {
            echo '不可重复处理';
            file_put_contents($path . 'notify_' . date('Ymd') . '.log', date('Y-m-d H:i:s') . "\n" . '不可重复处理' . "\n", FILE_APPEND);
            exit;
        }
        if ($order['amount'] != $count) {
            echo '金额不符';
            file_put_contents($path . 'notify_' . date('Ymd') . '.log', date('Y-m-d H:i:s') . "\n" . '金额不符' . "\n", FILE_APPEND);
            exit;
        }
        Db::startTrans();
        try {
            if ($status == 'Failed') {
                //修改订单状态
                db('otc_sell')->where(['orderNo' => $myOrderNo])->update(['status' => -1]);

                //卖币失败，给客户退回余额
                $old_balance = db('user_coin')->where(['user_id' => $order['user_id'], 'coin_id' => $order['coin_id']])->lock(true)->value('balance');
                $new_balance = bcadd($old_balance, $order['amount'], 8);
                db('user_coin')->where(['user_id' => $order['user_id'], 'coin_id' => $order['coin_id']])->update(['balance' => $new_balance]);
                //日志
                Db('log_coin')->insert([
                    'user_id' => $order['user_id'],
                    'coin_id' => $order['coin_id'],
                    'type' => 121,
                    'num' => $order['amount'],
                    'amount' => $old_balance,
                    'balance' => $new_balance,
                    'addtime' => time(),
                    'status' => 1,
                    'remark' => 'OTC出售退还',
                    'union' => 'otc_sell',
                    'union_id' => $order['id'],
                ]);
                Db::commit();
                file_put_contents($path . 'notify_' . date('Ymd') . '.log', date('Y-m-d H:i:s') . "\n" . $msg . "\n", FILE_APPEND);
                echo $msg;
            }
            if ($status == 'Done' && $count >= $order['amount']) {
                //修改订单状态
                db('otc_sell')->where(['orderNo' => $myOrderNo])->update(['status' => 1]);
                Db::commit();
                echo 'OK';
            }
        } catch (Exception $e) {
            file_put_contents($path . 'notify_' . date('Ymd') . '.log', date('Y-m-d H:i:s') . "\n" . $e->getMessage() . "\n", FILE_APPEND);
            Db::rollback();
            echo 'fail';
        }
    }

    /**
     * 验签
     */
    public static function verify($data, $sign)
    {
        $mySign = self::sign($data);
        return strcmp($mySign, $sign) == 0;
    }


    /**
     * 签名
     */
    public function sign($data)
    {
        ksort($data);
        $srcStr = '';
        foreach ($data as $k => $v) {
            if (!self::nullOrEmpty($v) && $k != 'sign') {
                $srcStr .= ($k . '=' . $v . '&');
            }
        }
        $srcStr .= ('key=' . 'e1804df9557fb9dfd35781c3d9b9b43e');
        return md5($srcStr);
    }

    /**
     * 检查字符串是否有效
     */
    public function nullOrEmpty($str)
    {
        return (!isset($str) || trim($str) === '');
    }
}
