<?php
/**
 * Created by PhpStorm.
 * User: feisha
 * Date: 2018/9/25
 * Time: 下午9:15
 */

namespace app\api\controller;

use think\Controller;
use think\response\Json;

class TradingView extends Controller
{

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        header("Access-Control-Allow-Origin: *");
    }

    function time()
    {
        //exit(time() . '');
        return Json(time());
    }

    function config()
    {
        return Json(json_decode('{"supports_time":true,"supports_group_request":false,"supports_search":true,"supports_marks":true,"supports_timescale_marks":true,"supported_resolutions":["1","5","15","30","60","1D","1W"]}'));
    }

    function symbol_info()
    {
        echo json_decode('');
    }

    function symbols($symbol)
    {
        return Json(json_decode('{"symbol":"' . $symbol . '","pointvalue":null,"type":"stock","minmov2":2,"exchange-traded":"","exchange-listed":"","timezone":"Asia/Shanghai","has_no_volume":false,"ticker":"' . $symbol . '","session":"24x7","supported_resolutions":["1","5","15","30","60","1D","1W"],"has_intraday":true,"name":"","pricescale":10000.0,"minmov":1}'));
    }

    function timescale_marks()
    {
        $data = [
            '"{id:\"tsm1\",color:\"red\",label:\"A\",time:1523577600,tooltip:\"\"}"',
            '"{id:\"tsm2\",color:\"blue\",label:\"D\",time:1523232000,tooltip:\"\"}"',
            '"{id:\"tsm3\",color:\"green\",label:\"D\",time:1522972800,tooltip:\"\"}"',
            '"{id:\"tsm4\",color:\"#999999\",label:\"E\",time:1522281600,tooltip:\"\"}"',
            '"{id:\"tsm7\",color:\"red\",label:\"E\",time:1520985600,tooltip:\"\"}"',
        ];
        return Json($data);
    }

    function marks()
    {
        return Json(json_decode('{"id":[0,1,2,3,4,5],"labelFontColor":["white","white","red","#FFFFFF","white","#000"],"time":[1523577600,1523232000,1522972800,1522972800,1522281600,1520985600],"label":"","minSize":[14,28,7,40,7,14],"color":["red","blue","green","red","blue","green"]}'));
    }


    function history($symbol, $resolution, $from, $to)
    {
        $coin_name = explode("_", $symbol);
        $coin = db('coin')->where('name', $coin_name[0])->field('coin_id,is_trade')->find();
        if ($coin['is_trade'] == 0) {
            $data = db('log_trade_day')->where('exch_coin_id', $coin['coin_id'])->field('open_price,close_price,high_price,low_price,addtime,num')->select();

            if ($data) {
                foreach ($data as $k => $v) {
                    $new_data['c'][] = floatval($v['close_price']);
                    $new_data['h'][] = floatval($v['high_price']);
                    $new_data['l'][] = floatval($v['low_price']);
                    $new_data['o'][] = floatval($v['open_price']);
                    $new_data['t'][] = floatval($v['addtime']);
                    $new_data['v'][] = floatval($v['num']);
                }
                $new_data['s'] = 'ok';

                return Json($new_data);
            }
        } else {
            // 修改部分问题
//            if ($resolution == '1D') $resolution = 24 * 60;
//            if ($resolution == 'D') $resolution = 24 * 60 * 7;
//            $times = 60 * $resolution;

            if ($resolution == '1') {
                $type = '1min';
            } elseif ($resolution === '5') {
                $type = '5min';
            } elseif ($resolution === '15') {
                $type = '15min';
            } elseif ($resolution === '30') {
                $type = '30min';
            } elseif ($resolution === '60') {
                $type = '1hour';
            } elseif ($resolution === '1D') {
                $type = '1day';
            } elseif ($resolution === 'D') {
                $type = '1week';
            }

            //$symbol = str_replace('_', '', $symbol);

            $coin_name = explode('_', $symbol)[0];

            $data = http('http://api.zb.cn/data/v1/kline?market=' . $symbol . '&type=' . $type)['data'];

            if ($data) {
                $price['price'] = $data[sizeof($data) - 1][4];
                if ($type == '1day') {
                    $price['open_price'] = $data[sizeof($data) - 1][1];
                }
                db('coin')->where('name', $coin_name)->update($price);
                foreach ($data as $k => $v) {
                    $new_data['c'][] = floatval($v[2]);
                    $new_data['h'][] = floatval($v[3]);
                    $new_data['l'][] = floatval($v[4]);
                    $new_data['o'][] = floatval($v[1]);
                    $new_data['t'][] = floatval($v[0] / 1000);
                    $new_data['v'][] = floatval($v[5]);
                }
                $new_data['s'] = 'ok';
                return Json($new_data);
            }
        }
    }

}