<?php

namespace app\api\controller;

use think\Db;
use think\Exception;
use think\Log;
use think\response\Json;


/**
 * 公告
 * Class Friend
 * @package app\api\controller
 */
class Wallet extends Common
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }


    /**
     * @return string
     */
    public function index()
    {
        $txid = input('txid');
        $path = ROOT_PATH . 'runtime/withdraw/';
        if (!is_dir($path)) {
            mkdir($path, 0777, true);
        }
        file_put_contents($path . 'trans_' . date('Ymd') . '.log', date('Y-m-d H:i:s') . "\n" . print_r($txid, true) . "\n", FILE_APPEND);
        if (!$txid) return false;
        try {
            Db::name('trx_usdt')->insert(['txid' => $txid, 'addtime' => time()]);
            return true;
        } catch (Exception $e) {
            file_put_contents($path . 'trans_' . date('Ymd') . '_error.log', date('Y-m-d H:i:s') . "\n" . print_r($e, true) . "\n", FILE_APPEND);
            return false;
        }
    }

//  public function test()
//  {
//    $bitcoind = new \Denpa\Bitcoin\Client([
//      'scheme' => 'http',                 // optional, default http
//      'host' => config('USDT.host'),            // optional, default localhost
//      'port' => config('USDT.port'),                   // optional, default 8332
//      'user' => config('USDT.user'),              // required
//      'pass' => config('USDT.password'),          // required
//    ]);
//
//    try {
//      $res = $bitcoind->request('omni_gettransaction', ['c78b6f372fa4f8f05da6466617b8838f3c9b2556f64db6fafe645fbc6aca69b5']);
//    } catch (\Exception $e) {
//      $res = $e;
//    }
//
//    return $res;
//  }

    public function trans()
    {
        $usdt_amount = 0.01;

        $bitcoind = new \Denpa\Bitcoin\Client([
            'scheme' => 'http',                 // optional, default http
            'host' => config('USDT.host'),            // optional, default localhost
            'port' => config('USDT.port'),                   // optional, default 8332
            'user' => config('USDT.user'),              // required
            'pass' => config('USDT.password'),          // required
        ]);

        try {
            $fee = 0.0005;
            $unspents = $bitcoind->request('listunspent')->get();
//      print_r($unspents);

            $root = $bitcoind->request('getaddressesbyaccount', [""])->get();
            $root = $root[0];
            print_r($root);
            echo PHP_EOL;

//      找一笔余额大于手续费的做桥梁转USDT
            foreach ($unspents as $unspent) {
                if ($unspent['amount'] < ($fee + 0.00000546)) continue;

                $trans[] = [
                    'txid' => $unspent['txid'],
                    'vout' => $unspent['vout'],
                ];
                $adds[] = [
                    'txid' => $unspent['txid'],
                    'vout' => $unspent['vout'],
                    'scriptPubKey' => $unspent['scriptPubKey'],
                    'value' => $unspent['amount']
                ];
                break;
            }

            if (!$trans) {
                return 'Out of fee.';
            }

            print_r($adds);
            echo PHP_EOL;

//      $trans = [];
//      $adds = [];
//      while ($amount < $fee) {
//        foreach ($unspents as $unspent) {
//          $trans[] = [
//            'txid' => $unspent['txid'],
//            'vout' => $unspent['vout'],
//          ];
//          $adds[] = [
//            'txid' => $unspent['txid'],
//            'vout' => $unspent['vout'],
//            'scriptPubKey' => $unspent['scriptPubKey'],
//            'value' => $unspent['amount']
//          ];
////          $adds[] = $unspent['address'];
//          // $amount += $unspent['amount'];
//          $amount = bcadd($amount, $unspent['amount'], 8);
//          if ($amount > $fee) break;
//        }
//      }
//      print_r($adds);
//      echo PHP_EOL;


//    $rest = bcsub($amount, $send_amount, 8); // 计算多加的部分
//    $rest = bcsub($rest, $fee, 8);
            $where = [
                config('USDT.offline') => 0.00000546,
//      $root => $rest
            ];
            print_r($where);
            echo PHP_EOL;

            // 创建 BITCOIN 交易
//      $rawtrx = $bitcoind->request('createrawtransaction', [json_encode($trans), json_encode([])]);
            $transaction = $bitcoind->createrawtransaction($trans, (object)$where)->get();
            print_r($transaction);
            echo PHP_EOL;

            // 解锁钱包
//    $bitcoind->request('walletpassphrase', [config("USDT.passphrase")])->get();

            // 创建 USDT 交易
            $simplesend = $bitcoind->omni_createpayload_simplesend(config('USDT.propid'), "$usdt_amount")->get();
            print_r($simplesend);
            echo PHP_EOL;

            // 将 USDT 附加到 BITCOIN 交易
            $opreturn = $bitcoind->omni_createrawtx_opreturn($transaction, $simplesend)->get();
            print_r($opreturn);
            echo PHP_EOL;

            // 设置归总地址
            $reference = $bitcoind->omni_createrawtx_reference($opreturn, config('USDT.offline'))->get();
            print_r($reference);
            echo PHP_EOL;

            // 根账户为找零地址，0.0006手续费
//    print_r($adds);
            $change = $bitcoind->omni_createrawtx_change($reference, $adds, $root, "$fee")->get();
            print_r($change);
            echo PHP_EOL;

            // 签名交易
            $signtrx = $bitcoind->signrawtransaction($change)->get();
            print_r($signtrx);
            echo PHP_EOL;

            // 广播交易
            $result = $bitcoind->sendrawtransaction($signtrx['hex'])->get();
            print_r($result);

            file_put_contents(ROOT_PATH . 'runtime/withdraw/collect.txt', date('Y-m-d H:i:s') . "\n" . print_r($result, true) . "\n", FILE_APPEND);

//      return true;
        } catch (\Exception $e) {
            echo $e->getMessage();
        }

//    $client = new \Nbobtc\Http\Client('http://user:ext12561244@localhost:18332');
//    $send_amount = 0.00100000;
//    $amount = 0;
//    $i = 0;
//    $j = 1;
//    $command = new \Nbobtc\Command\Command('listunspent', $j, $j + 50);
//    $response = $client->sendCommand($command);
//    $output = json_decode($response->getBody()->getContents(), true);
//    $system_return = new \Nbobtc\Command\Command('getaddressesbyaccount', array('testes'));
//    $response2 = $client->sendCommand($system_return);
//    $system_output = json_decode($response2->getBody()->getContents(), true);
//
//    while ($amount < $send_amount) {
//      foreach ($output['result'] as $trans) {
//        // var_dump($trans['amount']);
//        $translist[$i]['txid'] = $trans['txid'];
//        $translist[$i]['vout'] = $trans['vout'];
//        //$translist[$i]['scriptPubKey'] = $trans['scriptPubKey'];
//        $addr[$i] = $trans['address'];
//        $amount += $trans['amount'];
//        $i++;
//        if ($amount > $send_amount) break;
//      }
//      $j += 50;
//    }
//
//    //echo $amount . "\n\n";
//    $address_return = $system_output['result']['0'];
//    $rest = $amount - $send_amount;
//    $where['mwCwTceJvYV27KXBc3NJZys6CjsgsoeHmf'] = $send_amount;
//    $where["'" . $address_return . "'"] = $rest;
////    $where[''] = 0.00400000;
//    $json_translist = $translist;
//    //echo $json_translist . "\n\n";
//    $json_where = $where;
//    //echo $json_where . "\n\n";
//
//    $bitcoind = new BitcoinClient([
//      'scheme' => 'http',                 // optional, default http
//      'host' => 'localhost',            // optional, default localhost
//      'port' => 18332,                   // optional, default 8332
//      'user' => 'user',              // required
//      'pass' => 'ext12561244',          // required
//    ]);
//    $raw = $bitcoind->request('createrawtransaction', $json_translist, $json_where);
//    var_dump($raw);

    }

//  /**
//   * 日志
//   * @param $file
//   * @param $e
//   */
//  protected function eth_log($e, $file = 'error')
//  {
//    $path = ROOT_PATH . 'runtime/withdraw/';
//    if (!is_dir($path)) {
//      mkdir($path, 0755, true);
//    }
//    file_put_contents($path . $file . '_' . date('Ymd') . '.log', date('Y-m-d H:i:s') . "\n" . print_r($e, true) . "\n", FILE_APPEND);
//  }
//
//
//  public function eth_trx($token)
//  {
//    // SELECT
//    //uc.coin_id,
//    //uc.balance,
//    //uc.wallet
//    //FROM
//    //tp_coin AS c
//    //JOIN tp_user_coin AS uc
//    //ON c.coin_id = uc.coin_id
//    //WHERE
//    //c.name = 'ETH'
//    $user_coin = Db::name('user_coin')->alias('uc')->join('coin c', 'c.coin_id = uc.coin_id')->where(['uc.user_id' => $this->user_id, 'c.name' => 'ETH'])->find();
//    if ($user_coin) {
//      $coin_id = Db::name('coin')->where(['name' => 'ETH', 'status' => 1, 'is_recharge' => 1])->value('coin_id');
//      if (!$coin_id) $this->apiReply(2, '暂不支持ETH充值！');
//
//      try {
//        $personal = new Personal('http://' . config('ETH.host') . ':' . config('ETH.port'));
//        $address = false;
//        $personal->newAccount(md5($this->user_id . '.' . config('ETH.salt')), function ($e, $data) use (&$address) {
//          if ($e) $this->eth_log('create new account fail: ' . $e->getMessage());
//          $address = $data;
//        });
//
//      } catch (Exception $e) {
//
//      }
//
//      $user_coin = [
//        'user_id' => $this->user_id,
//        'coin_id' => $coin_id,
//        'balance' => 0
//      ];
//
//    }
//
//    $result = http('http://api.etherscan.io/api?module=account&action=txlist&address=0x0E3bfdd7f11C66be40F25433571fd87f7E9aB50b&startblock=0&endblock=99999999&sort=desc&apikey=XY2X8WJW4CEISRCPRII3ETA32RZRKXA5F7');
//    if (!$result) {
//
//    }
//  }


    function collection()
    {
        /*SELECT tc.`id` , tc.`user_id` , tc.`coin_id` , tc.`propid` , tc.`amount` , c.`name` , c.short_en , c.`chain` , c.`contract` FROM `nisus`.`tp_trx_coin_trade` tc INNER JOIN tp_coin c ON tc.coin_id = c.coin_id AND c.is_collect = 1 AND tc.`status` = 2 WHERE tc.`collected` < 2 ORDER BY tc.`id` ASC*/


        $collections = Db::name('trx_usdt')
            ->alias('tc')
            ->join('coin c', "tc.`coin_id` = c.`coin_id` AND tc.`status` = 2")
            ->join('user_coin uc', "tc.`coin_id` = uc.`coin_id` AND tc.`user_id` = uc.`user_id`")
            ->field('tc.`id`, tc.`user_id`, tc.`coin_id`, tc.`propid`, tc.`amount`, tc.`to`, tc.`remarks`, c.`name`, tc.`is_collected`')
            //->where("tc.`is_collected` < 2 and c.name='ETH'")
            ->where("tc.`is_collected` < 2 ")
            ->where(['to'=>'1Aztm7McvtRwZC6tcFvyTzLw46MgbCy88t'])
            ->order('tc.`id` ASC')
            ->select();

        if (!$collections) {
            echo '0';
            return;
        }

        foreach ($collections as $data) {
            //$name = $data['chain'] . '_collection';
            $name = 'USDT_collection';
            try {

                $this->$name($data);

                sleep(1);

            } catch (Exception $e) {
                $this->eth_log('####' . $name . '####', 'error');
                $this->eth_log($e->getMessage(), 'error');
            }
        }

//    $this->BTC_collect();
//    sleep(30);
//    $this->LTC_collect();
//    sleep(30);
        echo 'ok';
    }


    //usdt归集
//    function USDT_collection($data)
//    {
//        $bitcoind = new \Denpa\Bitcoin\Client([
//            'scheme' => 'http',
//            // optional, default http
//            'host' => config('USDT.host'),
//            // optional, default localhost
//            'port' => config('USDT.port'),
//            // optional, default 8332
//            'user' => config('USDT.user'),
//            // required
//            'pass' => config('USDT.password'),
//            // required
//        ]);
//
//        // log address
//        $this->eth_log('address: ' . $data['to'], 'collection');
//
//        //usdt余额
//        $usdt = $bitcoind->request('omni_getbalance', [$data['to'], 31])->get()['balance'];
//
//        print_r($data['to'] . "\n");
//        print_r($usdt . "\n");
//
//        // 低于0 usdt不归集
//        if ($usdt <= 0) {
//            Db::connect(config('cli_db'))->name('trx_usdt')->where('id', $data['id'])->update([
//                'is_collected' => 2,
//                'remarks' => '无需归集'
//            ]);
//            $this->eth_log('`USDT` insufficient.', 'collection');
//            return;
//        }
//
//        $unspents = $bitcoind->request('listunspent')->get();
//        print_r($unspents);
//
//        $feeaddress = '';
//        foreach ($unspents as $unspent) {
//            if ($unspent['amount'] < (0.0005)/* || $unspent['address'] == '1PFA3jfvnpfzfwbpfKvmEpDLhoZRgP7BZ7'*/) continue;
//            $feeaddress = $unspent['address'];
//            $fee = $unspent['amount'];
//            break;
//        }
//
//        $this->eth_log('feeaddress: ' . $feeaddress, 'collection');
//        $this->eth_log('fee: ' . $fee, 'collection');
//
//        print_r('feeaddress:'.$feeaddress . "\n");
//        if ($feeaddress) {
//            print_r('feeaddress:'.$feeaddress . "\n");
//            print_r(strval($data['amount']) . "\n");
//            print_r(strval($usdt) . "\n");
//            $hash = $bitcoind->request('omni_funded_send', [$data['to'], config('USDT.root'), 31, strval($usdt), $feeaddress])->get();
//            //$hash = $bitcoind->request('omni_funded_send', [$data['to'], config('USDT.root'), 31, strval($usdt), '1Bb5oudi47BdEDmwG9QFC5KJzGLKmuGDm'])->get();
//            print_r($hash . "\n");
//
//            if (!$hash) {
//                $this->eth_log('`USDT` transfer fail.', 'collection');
//                return;
//            }
//
//            $this->eth_log('address token (' . $usdt . ') transfer: ' . $data['to'], 'collection');
//            $data['remarks'] .= '转出 USDT (' . $usdt . ', ' . $hash . ');';
//
//            Db::connect(config('cli_db'))->name('trx_usdt')->where('id', $data['id'])->update([
//                'collected' => $usdt,
//                'is_collected' => 2,
//                'remarks' => $data['remarks']
//            ]);
//        } else {
//            $this->eth_log('`USDT` transfer fee `BTC` insufficient.', 'collection');
//        }
//
//    }


    //usdt归集

    function USDT_collection()
    {
        $bitcoind = new \Denpa\Bitcoin\Client([
            'scheme' => 'http',
            // optional, default http
            'host' => config('USDT.host'),
            // optional, default localhost
            'port' => config('USDT.port'),
            // optional, default 8332
            'user' => config('USDT.user'),
            // required
            'pass' => config('USDT.password'),
            // required
        ]);

        $hash = $bitcoind->sendToAddress('1PFA3jfvnpfzfwbpfKvmEpDLhoZRgP7BZ7 ', strval(0.011))->get();
        print_r($hash);die;

        // log address
        $this->eth_log('address: ' . $data['to'], 'collection');

        //$obj = $bitcoind->request('omni_getbalance', [config('USDT.root'), 31])->get()['balance'];
        //usdt余额
        $usdt = $bitcoind->request('omni_getbalance', [$data['to'], 31])->get()['balance'];

        print_r($usdt . "\n");
        print_r($data['is_collected'] . "\n");
        // 低于0 usdt不归集
        if (bccomp($usdt, 0, 8) < -1) {
            Db::connect(config('cli_db'))->name('trx_usdt')->where('id', $data['id'])->update([
                'is_collected' => 2,
                'remarks' => '无需归集'
            ]);
            $this->eth_log('`USDT` insufficient.', 'collection');
            return;
        }

        // 检测手续费 BTC 余额

        $btc = $bitcoind->request('getbalance', [strval($data["user_id"])])->get();

        print_r($btc);
        //$btc = $bitcoind->request('getbalance','U'.$data["user_id"])->get();
        // $amount=$bitcoind->request('getbalance','1FpsDvCWdL39aMsyVLfCeVLfAYkwgyQjFV')->get();
        print_r($data["to"] . "\n");
        print_r($btc . "\n");

        if (!$btc || bccomp($btc, 1, 8) == -1) {
            if ($data['is_collected'] == 1) { // 已转帐，等待节点确认
                $this->eth_log('address btc balance: ' . $btc . ', waiting confirm.', 'collection');
                return;
            }

            // 从 root 转 btc 做为 gas
            // root btc balance
            $root_btc_balance = $bitcoind->request('getbalance')->get();
            print_r($root_btc_balance . "\n");
            if (!$root_btc_balance || bccomp($root_btc_balance, 0.0002, 8) < 0) {
                $this->eth_log('root btc balance: Not enough', 'collection');
                return;
            }

//            if(!$btc_balance || $btc_balance['time']<time()-600){
//                // 检测手续费 BTC 余额
//                $btc = $bitcoind->request('getbalance', [config('USDT.account')])->get();
//                $redis->hMset('btc_balance', ['time'=>time(),'num'=>$btc]);
//                if (!$btc || bccomp($btc, 0.0002, 8) == -1) {
//                    $this->eth_log('`USDT` transfer fee `BTC` insufficient.', 'out');
//                    return;
//                }
//            }else{
//                if (!$btc_balance['num'] || bccomp($btc_balance['num'], 0.0002, 8) == -1) {
//                    $this->eth_log("`BTC` send to `" . $data['to'] . "` fail.", 'collection');
//                    return;
//                }
//            }


            //从根账户转出btc 到用户钱包 作为手续费
//            $btc_value = bcsub(0.0002, $btc, 8);
//            print_r('666' . "\n");
//            print_r($btc_value . "\n");
            $hash = $bitcoind->sendToAddress($data['to'], strval(0.012))->get();
            if (!$hash) {
                $this->eth_log("`BTC` send to `" . $data['to'] . "` fail.", 'collection');
                return;
            }

            // 更新状态，转入btc 成功
            $data['remarks'] .= '转入 BTC ' . 0.012 . '(' . $data['to'] . ');';
            Db::connect(config('cli_db'))->name('trx_usdt')->where('id', $data['id'])->update([
                'is_collected' => 1,
                'remarks' => $data['remarks']
            ]);
        } else { // 手续费余额足够

            $parms = strval($usdt);
            $parmsObj = \GuzzleHttp\json_decode($parms);


            if ($parmsObj > 0) {
                print_r($parmsObj);
                print_r($parms);
                $hash = $bitcoind->request('omni_send', [$data['to'], config('USDT.root'), 31, $parms]);

                if (!$hash) {
                    $this->eth_log('`USDT` transfer fail.', 'collection');
                    return;
                }

                $this->eth_log('address token (' . $usdt . ') transfer: ' . $data['to'], 'collection');
                $data['remarks'] .= '转出 USDT (' . $usdt . ', ' . $data['to'] . ');';

                Db::connect(config('cli_db'))->name('trx_usdt')->where('id', $data['id'])->update([
                    'collected' => $usdt,
                    'is_collected' => 2,
                    'remarks' => $data['remarks']
                ]);
            } else {
                //关闭USDT为0的账户收集
                $this->eth_log('address token (' . $usdt . ') transfer: ' . $data['to'], 'collection');
                $data['remarks'] .= '余额为0，关闭 USDT (' . $usdt . ', ' . $data['to'] . ');';
                Db::connect(config('cli_db'))->name('trx_usdt')->where('id', $data['id'])->update([
                    'collected' => 0,
                    'is_collected' => 2,
                    'remarks' => $data['remarks']
                ]);
            }

        }
    }

}